#' @title Cores dos Times Brasileiros
#' @description
#' Hexcode da cor principal do brasão de cada time que passou pela Série A do Brasileirão de 2003 à 2023
#' @format Vetor com 47 elementos, todos do tipo string
#' @export
coresBR <- function(){
  corBr <- c(`América-MG` = "#007f4e",
           `América-RN` = "#E41920",
           `Athletico-PR` = "#E5050F",
           `Atlético-GO` = "#DC1212",
           `Atlético-MG` = "black",
           `Atlético-PR` = "#E5050F",
           `Avaí FC` = "#00679A",
           `Barueri` = "#FECE02",
           `Botafogo` = "black",
           `Brasiliense-DF` = "#FFDE00",
           `Ceará SC` = "black",
           `Chapecoense` = "#00813A",
           `Corinthians` = "#231f20",
           `Coritiba FC` = "#00534C",
           `Criciúma EC` = "#FDD116",
           `Cruzeiro` = "#2F529E",
           `CSA` = "#0A275D",
           `Cuiabá-MT` = "#FBD800",
           `EC Bahia` = "#006CB5",
           `EC Vitória` = "#ff1100",
           `Figueirense FC` = "black",
           `Flamengo` = "#C52613",
           `Fluminense` = "#870a28",
           `Fortaleza` = "#006cb5",
           `Goiás` = "#01481E",
           `Goiás EC` = "#01481E",
           `Grêmio` = "#0d80bf",
           `Guarani` = "#006C51",
           `Internacional` = "#c20c18",
           `Ipatinga FC` = "#48887B",
           `Joinville-SC` = "#343232",
           `Juventude` = "#00922E",
           `Náutico` = "#ED1C24",
           `Palmeiras` = "#006437",
           `Paraná` = "#1C4189",
           `Paysandu SC` = "#0075C9",
           `Ponte Preta` = "black",
           `Portuguesa` = "#EE221C",
           `RB Bragantino` = "#D61E3F",
           `Santa Cruz` = "#B11C18",
           `Santo André` = "#0A2572",
           `Santos` = "black",
           `Santos FC` = "black",
           `São Caetano` = "#222568",
           `São Paulo` = "#fe0000",
           `Sport Recife` = "#ffd900",
           `Vasco da Gama` = "black")
  return(corBr)
}
